version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:023553074824:task-definition/my-app-task:4"
        LoadBalancerInfo:
          ContainerName: "my-app"
          ContainerPort: 8000
