version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - pytest test_main.py
  build:
    commands:
      - >
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS 
        --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker build -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - "**/*"
  discard-paths: no
